### ISSUE TITLE
[Solved] How to adjust the config after adding a new gipper?

### ISSUE THREAD

**Issue by wangyan-hlab** [columbia-ai-robotics/scalingup#10]
Hi,

I have added a Robotiq85 gripper to the UR5 robot.

When I tried to generate some data, it cannot sample any successful trajectories because of **collision** or **not touch the toy**.

I am trying to change some configs in ```evaluation/env/config/default.yaml```, but I am totally confused of the meaning the parameters (like ```max/min_pushin_dist``` and ```grasp_primitive_z_pushin/backup```) and have no direction how to adjust them. 😭 

If anyone got any idea, I am really appreciate it.

Best regards

**Comment by wangyan-hlab** [comment]
Hi, @huy-ha 

Maybe I have made a bad decision:
 
As the default wsg50+finray gripper is a simple parallel gripper, the gipper links are just two fingers.
But the Robotiq85 gripper is a more complicated one with several links (drivers, followers, spring links ...), and the driver joints are revoluting instead of sliding ones.

Things become complex when the gripper is changed to Robotiq85, and I am still trying to walk through these issues to make it work.

I will report more after some time.

**Comment by wangyan-hlab** [comment]
Finally, I figure out the solution and would like to report here:

In ```scalingup/environment/mujoco/$ROBOTNAME.py```, one has to correctly define the ```end_effector_links``` which have collision models to contact the objects. 
Make sure that in the ```.xml``` file of the gripper, the ```end_effector_links``` you chose HAVE collision models. 
I believe that my configuration didn't work because of it.

After setting these correctly, it works well without changing anything else.

Hope my experience would help.

**Comment by huy-ha** [comment]
I'll make sure to add extra information and documentation to the codebase for `EnvConfig` parameters as well as more instructions on adding new embodiments!
