### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Alpslee** [columbia-ai-robotics/scalingup#4]
from scalingup.environment.mujoco.table_top_pick_and_place import TableTopPickAndPlace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/content/scalingup/scalingup/environment/mujoco/table_top_pick_and_place.py", line 5, in <module>
    from scalingup.environment.mujoco.mujocoEnv import (
ImportError: cannot import name 'DynamicMujocoUR5Env' from 'scalingup.environment.mujoco.mujocoEnv' (/content/scalingup/scalingup/environment/mujoco/mujocoEnv.py)

I run it on colab terminal, need some help, thanks

**Comment by wangyan-hlab** [comment]
I think maybe you can just comment the *DynamicMugocoUR5Env* line, as it is not referenced in the script.
