### ISSUE TITLE
drawer texture difference

### ISSUE THREAD

**Issue by yangsizhe** [columbia-ai-robotics/scalingup#9]
Glad to see this wonderful work! I noticed that the texture of the drawer I visualized is different from what's shown on the project website (https://www.cs.columbia.edu/~huy/scalingup/static/videos/teaser-crf30.mp4). The drawer texture on the project website appears to be more realistic. How can I access the drawer texture as seen on the project website?

**Comment by huy-ha** [comment]
Thanks for the kind words! 

The video you linked were rendered using Blender for visualization purposes. Instructions for using that visualization pipeline is [here](https://github.com/columbia-ai-robotics/scalingup/blob/master/docs/visualization.md) and I think the materials for the drawer are from [BlenderKit](https://www.blenderkit.com/get-blenderkit/44a70fd1-c1ea-4835-a2db-e9593e0bbf57/). That visualization pipeline is not used for data generation, training and evaluation.
